import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
function CPMark({ id }) {
    const s = { stroke: "#2B1F3D", strokeWidth: 1.4, fill: "none", strokeLinecap: "round", strokeLinejoin: "round" };
    if (id === "google") {
        return (_jsxs("svg", { width: "20", height: "20", viewBox: "0 0 22 22", "aria-hidden": "true", children: [_jsx("rect", { x: "3", y: "5", width: "16", height: "14", rx: "3", ...s }), _jsx("path", { d: "M3 9.5h16M7 3.5v4M15 3.5v4", ...s }), _jsx("path", { d: "M8.5 13.5l2 2 3.5-4", ...s })] }));
    }
    return (_jsxs("svg", { width: "20", height: "20", viewBox: "0 0 22 22", "aria-hidden": "true", children: [_jsx("rect", { x: "3", y: "5", width: "16", height: "14", rx: "3", ...s }), _jsx("path", { d: "M3 9.5h16M7 3.5v4M15 3.5v4", ...s }), _jsx("circle", { cx: "8", cy: "13.5", r: "0.9", fill: "#2B1F3D" }), _jsx("circle", { cx: "11", cy: "13.5", r: "0.9", fill: "#2B1F3D" }), _jsx("circle", { cx: "14", cy: "13.5", r: "0.9", fill: "#2B1F3D" }), _jsx("circle", { cx: "8", cy: "16", r: "0.9", fill: "#2B1F3D" }), _jsx("circle", { cx: "11", cy: "16", r: "0.9", fill: "#2B1F3D" })] }));
}
function Check() {
    return (_jsx("svg", { width: "13", height: "13", viewBox: "0 0 14 14", "aria-hidden": "true", children: _jsx("path", { d: "M2.5 7.3L5.4 10L11.5 4", stroke: "currentColor", strokeWidth: "1.9", fill: "none", strokeLinecap: "round", strokeLinejoin: "round" }) }));
}
function StepSection({ index, title, description, children, }) {
    return (_jsxs("div", { className: "cp-block", children: [_jsxs("div", { className: "cp-block-head", children: [_jsx("span", { className: "cp-idx", children: index }), _jsxs("div", { className: "cp-block-heir", children: [_jsx("div", { className: "cp-block-title", children: title }), _jsx("div", { className: "cp-block-desc", children: description })] })] }), children] }));
}
export function CalendarsProjectionStep({ rows, selectedKeys, projectionKey, integrationsError, onToggleAvailability, onSelectProjection, toLabel, }) {
    const writableRows = rows.filter((row) => row.canWrite);
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "onb-step-head", children: [_jsx("span", { className: "eyebrow", children: "Step 02 \u00B7 Calendars & projection" }), _jsxs("h2", { children: ["Select calendars that shape ", _jsx("em", { children: "availability and writeback." })] }), _jsx("p", { children: "Toggle the calendars bunnyCal should check for conflicts, then choose the one calendar that receives confirmed bookings." })] }), integrationsError ? _jsx("p", { className: "onb-error", children: integrationsError }) : null, _jsxs("div", { className: "cp-wrap", children: [_jsx(StepSection, { index: "1", title: "Availability calendars", description: "bunnyCal checks these for conflicts, so it only ever offers times you're genuinely free.", children: _jsx("div", { className: "cp-list", children: rows.map((row) => {
                                const on = selectedKeys.has(row.key);
                                return (_jsxs("div", { className: "cp-lrow", children: [_jsxs("div", { className: "cp-mcal", children: [_jsx("span", { className: "mk", style: { background: "var(--lilac-soft)", borderColor: "var(--lilac)" }, children: _jsx(CPMark, { id: String(row.provider).toLowerCase() }) }), _jsxs("span", { className: "cp-mcal-text", children: [_jsx("span", { className: "nm", children: row.label.replace(/@.*/, "").trim() || row.label }), _jsx("span", { className: "sb", children: toLabel(row.provider) })] })] }), _jsx("span", { className: "cp-lstate" + (on ? " on" : ""), children: on ? "Checking conflicts" : "Not checked" }), _jsx("button", { type: "button", role: "switch", "aria-checked": on, className: "onb-toggle toggle" + (on ? " on" : ""), onClick: () => onToggleAvailability(row), "aria-label": `Check ${row.label} for free/busy` })] }, row.key));
                            }) }) }), _jsxs(StepSection, { index: "2", title: _jsxs(_Fragment, { children: ["Booking calendar ", _jsx("span", { className: "cp-wb", children: "writeback" })] }), description: "Pick the one calendar where every confirmed booking is written. Only this calendar is ever edited.", children: [_jsx("div", { className: "cp-dest-grid", role: "radiogroup", "aria-label": "Booking destination calendar", children: writableRows.map((row) => {
                                    const selected = projectionKey === row.key;
                                    return (_jsxs("button", { type: "button", role: "radio", "aria-checked": selected, className: "cp-dest" + (selected ? " on" : ""), onClick: () => onSelectProjection(row.key), children: [_jsx("span", { className: "cp-dest-mark", style: { background: "var(--lilac-soft)", borderColor: "var(--lilac)" }, children: _jsx(CPMark, { id: String(row.provider).toLowerCase() }) }), _jsxs("span", { className: "cp-dest-body", children: [_jsxs("span", { className: "cp-dest-name", children: [_jsx("span", { className: "cp-swatch", style: { background: row.provider === "microsoft" ? "#BBC9DF" : "#B8A6DD" } }), row.label.replace(/@.*/, "").trim() || row.label] }), _jsx("span", { className: "cp-dest-sub", children: toLabel(row.provider) })] }), selected && _jsx("span", { className: "cp-dest-tick", children: _jsx(Check, {}) })] }, row.key));
                                }) }), !projectionKey && writableRows.length > 0 && (_jsxs("div", { className: "cp-note", role: "alert", children: [_jsxs("svg", { className: "ic", viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: "1.4", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("path", { d: "M8 1.5l6.5 11.5h-13L8 1.5z" }), _jsx("path", { d: "M8 6.5v3.2M8 11.8v.2" })] }), "Pick where confirmed bookings should land before you continue."] }))] }), _jsxs("span", { className: "cp-reassure", children: [_jsxs("svg", { width: "14", height: "14", viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: "1.35", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("rect", { x: "3.5", y: "7", width: "9", height: "6.5", rx: "1.5" }), _jsx("path", { d: "M5.5 7V5a2.5 2.5 0 0 1 5 0v2" })] }), "Encrypted in transit \u00B7 bunnyCal reads quietly and never overwrites your events."] })] }), rows.length === 0 && (_jsxs("div", { className: "cp-note", role: "alert", children: [_jsxs("svg", { className: "ic", viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: "1.4", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("path", { d: "M8 1.5l6.5 11.5h-13L8 1.5z" }), _jsx("path", { d: "M8 6.5v3.2M8 11.8v.2" })] }), "No connected calendar provider found. Connect at least one provider to select availability calendars."] }))] }));
}
