import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { ConfirmDialog } from "@/components/ConfirmDialog";
export function GuestBookingActionPanel({ canMutate, minRescheduleDateTime, cancelPending, reschedulePending, onCancelConfirm, onRescheduleSubmit, }) {
    const [rescheduleAt, setRescheduleAt] = useState("");
    const [confirmCancelOpen, setConfirmCancelOpen] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "mt-6 grid gap-4", children: [_jsxs("section", { className: "rounded-2xl border border-[#e2e8f0] p-4", children: [_jsx("h2", { className: "text-lg font-semibold text-[#0f172a]", children: "Cancel booking" }), _jsx("p", { className: "mt-1 text-sm text-[#64748b]", children: "Cancels this booking immediately. Duplicate submits are blocked while processing." }), _jsx("button", { type: "button", onClick: () => setConfirmCancelOpen(true), disabled: !canMutate || cancelPending || reschedulePending, className: "mt-4 rounded-xl bg-[#b91c1c] px-4 py-2 text-sm font-medium text-white disabled:opacity-60", children: cancelPending ? "Cancelling..." : "Cancel booking" })] }), _jsxs("section", { className: "rounded-2xl border border-[#e2e8f0] p-4", children: [_jsx("h2", { className: "text-lg font-semibold text-[#0f172a]", children: "Reschedule booking" }), _jsx("p", { className: "mt-1 text-sm text-[#64748b]", children: "Choose a new time. Request processing may be asynchronous with calendar providers." }), _jsxs("label", { className: "mt-3 block text-sm text-[#334155]", children: ["New start time", _jsx("input", { type: "datetime-local", value: rescheduleAt, min: minRescheduleDateTime, onChange: (event) => setRescheduleAt(event.target.value), className: "mt-1 w-full rounded-lg border border-[#d1d5db] px-3 py-2" })] }), _jsx("button", { type: "button", onClick: () => onRescheduleSubmit(rescheduleAt), disabled: !canMutate || cancelPending || reschedulePending, className: "mt-4 rounded-xl bg-[#0f172a] px-4 py-2 text-sm font-medium text-white disabled:opacity-60", children: reschedulePending ? "Submitting..." : "Reschedule booking" })] })] }), _jsx(ConfirmDialog, { open: confirmCancelOpen, tone: "danger", pending: cancelPending, title: "Cancel this booking?", description: "This action is safe to retry if it was already cancelled.", confirmLabel: "Yes, cancel booking", cancelLabel: "Keep booking", onCancel: () => setConfirmCancelOpen(false), onConfirm: async () => {
                    await onCancelConfirm();
                    setConfirmCancelOpen(false);
                } })] }));
}
