import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { Button, Input } from "@/ui/controls";
export function GuestBookingActionPanel({ canMutate, minRescheduleDateTime, cancelPending, reschedulePending, onCancelConfirm, onRescheduleSubmit, }) {
    const [rescheduleAt, setRescheduleAt] = useState("");
    const [confirmCancelOpen, setConfirmCancelOpen] = useState(false);
    const rescheduleDisabled = !canMutate || cancelPending || reschedulePending || !rescheduleAt;
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "mt-6 grid gap-4", children: [_jsxs("section", { className: "rounded-2xl border border-border-subtle bg-surface p-4", children: [_jsx("h2", { className: "text-lg font-semibold text-text-primary", children: "Cancel booking" }), _jsx("p", { className: "mt-1 text-sm text-text-secondary", children: "Cancel this booking if plans changed." }), _jsx(Button, { variant: "danger", size: "sm", onClick: () => setConfirmCancelOpen(true), disabled: !canMutate || cancelPending || reschedulePending, className: "mt-4", children: cancelPending ? "Cancelling..." : "Cancel booking" })] }), _jsxs("section", { className: "rounded-2xl border border-border-subtle bg-surface p-4", children: [_jsx("h2", { className: "text-lg font-semibold text-text-primary", children: "Reschedule booking" }), _jsx("p", { className: "mt-1 text-sm text-text-secondary", children: "Move this meeting to a new time while preserving booking continuity." }), _jsxs("label", { htmlFor: "guest-reschedule-start", className: "mt-3 block text-sm text-text-primary", children: ["New start time", _jsx(Input, { id: "guest-reschedule-start", type: "datetime-local", value: rescheduleAt, min: minRescheduleDateTime, onChange: (event) => setRescheduleAt(event.target.value), className: "mt-1" })] }), _jsx(Button, { variant: "primary", size: "sm", onClick: () => onRescheduleSubmit(rescheduleAt), disabled: rescheduleDisabled, className: "mt-4", children: reschedulePending ? "Submitting..." : "Reschedule booking" })] })] }), _jsx(ConfirmDialog, { open: confirmCancelOpen, tone: "danger", pending: cancelPending, title: "Cancel this booking?", description: "This action is safe to retry if it was already cancelled.", confirmLabel: "Yes, cancel booking", cancelLabel: "Keep booking", onCancel: () => setConfirmCancelOpen(false), onConfirm: async () => {
                    await onCancelConfirm();
                    setConfirmCancelOpen(false);
                } })] }));
}
