import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
import { useIntegrationState } from "@/state/IntegrationContext";
import { providerLabel, providerStatusTone } from "@/components/integrations/providerUi";
import { ProviderStatusRow } from "@/components/integrations/ProviderStatusRow";
export function DashboardParticipationSection() {
    const { calendarStatus, conferencingStatus } = useIntegrationState();
    const calendarRows = useMemo(() => Object.entries(calendarStatus), [calendarStatus]);
    const conferencingRows = useMemo(() => Object.entries(conferencingStatus), [conferencingStatus]);
    return (_jsxs("div", { className: "dash-section", children: [_jsx("div", { className: "dash-section-head", children: _jsxs("div", { children: [_jsxs("h2", { children: ["Service ", _jsx("em", { children: "participation" })] }), _jsx("div", { className: "sub", children: "How connected services quietly participate in scheduling coordination." })] }) }), _jsxs("div", { className: "panel", style: { marginBottom: 16 }, children: [_jsx("div", { className: "h", children: _jsxs("div", { children: [_jsx("h3", { children: "Calendar participation" }), _jsx("div", { className: "sub", children: "Sources that shape availability and booking confidence." })] }) }), calendarRows.length === 0 ? (_jsxs("div", { className: "dash-empty", style: { padding: "12px 0" }, children: [_jsx("h3", { children: "No calendar participants" }), _jsx("p", { children: "Connect a calendar provider to establish participation." })] })) : (_jsx("div", { style: { display: "grid", gap: 8 }, children: calendarRows.map(([provider, entry]) => (_jsx(ProviderStatusRow, { iconText: providerLabel(provider).slice(0, 1), name: providerLabel(provider), subtitle: "Calendar participation reported by backend orchestration.", meta: Array.isArray(entry.calendars) ? `${entry.calendars.length} calendars` : "Calendar details not reported", status: entry.status, statusClass: providerStatusTone(entry.status) }, provider))) }))] }), _jsxs("div", { className: "panel", children: [_jsx("div", { className: "h", children: _jsxs("div", { children: [_jsx("h3", { children: "Conferencing participation" }), _jsx("div", { className: "sub", children: "Providers that generate and attach call links." })] }) }), conferencingRows.length === 0 ? (_jsxs("div", { className: "dash-empty", style: { padding: "12px 0" }, children: [_jsx("h3", { children: "No conferencing participants" }), _jsx("p", { children: "Connect conferencing providers to enable call-link participation." })] })) : (_jsx("div", { style: { display: "grid", gap: 8 }, children: conferencingRows.map(([provider, entry]) => (_jsx(ProviderStatusRow, { iconText: providerLabel(provider).slice(0, 1), name: providerLabel(provider), subtitle: "Conferencing orchestration capability.", meta: "Guest meeting-link participation", status: entry.status, statusClass: providerStatusTone(entry.status) }, provider))) }))] })] }));
}
